FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ASP_Core.csproj", "."]
RUN dotnet restore "./ASP_Core.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./ASP_Core.csproj" -c $BUILD_CONFIGURATION -o /app/build

RUN dotnet publish "./ASP_Core.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ASP_Core.dll"]