name: Build with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Start Podman machine (if needed)
        run: podman machine start podman-machine

      - name: Set default Podman connection
        run: podman system connection default podman-machine

      - name: Check Podman status
        run: podman info

      - name: Build image
        run: podman build -t my-core-app .
