name: Build and Deploy ASP.NET Core with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Compose Up
        shell: powershell
        run: |
          wsl -d podman podman compose -f docker-compose.yml up -d --build

      - name: Check Podman Containers
        shell: powershell
        run: |
          wsl -d podman podman ps
