name: Podman Build

on:
  push:
    branches: [main]

jobs:
  podman-job:
    runs-on: [self-hosted, user]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Podman Compose Up
        run: |
          podman --version
          podman-compose --version
          podman-compose -f podman-compose.yml up -d --build

      - name: Show Running Containers
        run: podman ps

      - name: Copy .NET publish output from container
        run: podman cp asp_core:/app/publish ./dotnet-publish

      - name: Deploy to IIS (overwrite site folder)
        run: |
          Remove-Item -Recurse -Force "D:\Deploy\Core_Actions_Podman\*" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force ".\dotnet-publish\*" "D:\Deploy\Core_Actions_Podman"

      - name: Restart IIS Site
        run: |
          Import-Module WebAdministration
          Restart-WebSite -Name "Core_Actions_Podman"

          
      #- name: Build container image
      #  run: podman build -t myapp .

     # - name: Run container
      #  run: podman run -d -p 6025:80 myapp
