name: Build and Deploy Core App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # or your custom Podman runner

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image with Podman
        run: podman build -t my-core-app .

      - name: Stop and Remove Existing Container (Optional)
        run: |
          podman stop coreapp || true
          podman rm coreapp || true

      - name: Run New Container
        run: |
          podman run -d --name coreapp -p 8080:80 my-core-app
