name: Podman Build

on:
  push:
    branches: [main]

jobs:
  podman-job:
    runs-on: [self-hosted, user]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container image
        run: podman build -t myapp .

      - name: Run container
        run: podman run -d -p 4050:80 myapp
