name: Build and Deploy ASP.NET Core with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Podman Service in WSL
        shell: pwsh
        run: |
          wsl -d podman-machine podman system service -t 0 &

      - name: Compose Down (clean-up)
        shell: pwsh
        run: |
          wsl -d podman-machine podman compose down
          if ($LASTEXITCODE -ne 0) {
            Write-Host "compose down failed, continuing..."
          }

      - name: Build and Compose Up
        shell: pwsh
        run: |
          wsl -d podman-machine podman compose -f docker-compose.yml up -d --build

      - name: Check Podman Containers
        shell: pwsh
        run: |
          wsl -d podman-machine podman ps
