name: Build and Deploy ASP.NET Core with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Podman Service in WSL
        shell: powershell
        run: |
          Write-Host "Starting Podman service in background..."
          Start-Process "wsl.exe" -ArgumentList "-d podman-machine podman system service -t 0"

      - name: Compose Down (clean-up)
        shell: powershell
        run: |
          Write-Host "Shutting down any existing containers..."
          wsl -d podman-machine podman compose down
          if ($LASTEXITCODE -ne 0) {
            Write-Host "compose down failed or nothing to stop, continuing..."
          }

      - name: Build and Compose Up
        shell: powershell
        run: |
          Write-Host "Building and starting containers..."
          wsl -d podman-machine podman compose -f docker-compose.yml up -d --build

      - name: Check Running Containers
        shell: powershell
        run: |
          Write-Host "Listing running containers..."
          wsl -d podman-machine podman ps
