name: Build and Deploy ASP.NET Core with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Podman WSL VM
        shell: powershell
        run: |
          $wslDistros = wsl --list --verbose
          if ($wslDistros -match "podman\s+Stopped") {
            Write-Host "Starting podman WSL VM..."
            podman machine start
          } else {
            Write-Host "Podman WSL VM already running."
          }

      - name: Start Podman System Service
        shell: powershell
        run: |
          wsl -d podman podman system service -t 0 &

      - name: Compose Down (clean-up)
        shell: powershell
        run: |
          wsl -d podman podman compose down || Write-Host "compose down failed or nothing to stop, continuing..."

      - name: Build and Compose Up
        shell: powershell
        run: |
          wsl -d podman podman compose -f docker-compose.yml up -d --build

      - name: Check Podman Containers
        shell: powershell
        run: |
          wsl -d podman podman ps
